### ISSUE TITLE
vyriešiť priebežné generovanie máp

### ISSUE THREAD

**Issue by vidosuba** [TIS2018-FMFI/shmu#24]
možnosti  - postupné načítavanie
                  - predgenerovanie dát - zamietnuté, kôli výberu škály dát
                  - posielanie len súradníc a generovanie rastra na klientovi - seká mapu, kôli velkému množstvu      
                     štvorčekov - objektov, ktoré treba samostatne generovat

**Comment by vidosuba** [comment]
nová možnosť - generovanie v Rku, pekné mapy, problém, že sa vždy musia načítať knižnice odznova

**Comment by vidosuba** [comment]
finálne riešenie - generovanie tiffka v pythone, spracovanie leafletom a geotiffom v javascripte u klienta(XMLHttp request)

**Comment by pavlovator** [comment]
super tak to mozeme uzavriet :)
