### ISSUE TITLE
Návrh - finálna verzia

### ISSUE THREAD

**Issue by matobernat** [TIS2018-FMFI/shmu#25]
Dokončujem Návrh do finálnej podoby. je ešte niečo čo chýba? 

Ďalej, je na ľavej strane dokumentu osnova, no chýba v nej bod 3. stavový diagram používateľského rozhrania, možete mi prosím povedať ako ho tam vložím prípadne ho tam vložiť? ďakujem.

**Comment by matobernat** [comment]
https://docs.google.com/document/d/1HlI0xgw7FuXGlfh15JPt6lqOdpO3nwZ_7JbaEJzzeB0/edit?usp=sharing

link na pracovnú verziu návrhu - dá sa prezerať a upravovať len s odkazom

**Comment by vmizenkova** [comment]
mozete skontrolovat popis technologii, ci som nieco nepochopila zle a potom to mozem poslat dalej?

**Comment by vmizenkova** [comment]
prva verzia je odoslana cviciacemu

**Comment by matobernat** [comment]
je to ok
