### ISSUE TITLE
Návrh - pre Filipa 

### ISSUE THREAD

**Issue by matobernat** [TIS2018-FMFI/shmu#26]
Filip, bolo by fajn keby si farebne upravil časť v návrhu 4.4.1.2 Príklad konfiguračného súboru 

mohol by si bledomodro zvýrazniť veci ktoré sú na pevno a zelenou cestu ktorá sa môže meniť v závislosti od umiestnenia. teda aspoň tak som to pochopil že to je. ďakujem. spravil by som to ja ale neviem či to tak vobec je a neviem ani ktoré je cesta alebo čo :D :D

**Comment by pavlovator** [comment]
Dobre, viac to popisem a farebne oznacim :)

**Comment by vidosuba** [comment]
boli vytvorene samostatne ciastkove issue na dokoncenie navrhu

**Comment by pavlovator** [comment]
Mato, upravil som časť návrhu 4.4.1.2 (Príklad konfiguračného súboru) pozri sa prosim ťa, či si s tým spokojný.

**Comment by matobernat** [comment]
ano je to super, dakujem
