### ISSUE TITLE
navrh - popis technologii

### ISSUE THREAD

**Issue by vidosuba** [TIS2018-FMFI/shmu#29]
surne - treba spravit kôli dokončeniu návrhu

**Comment by vidosuba** [comment]
treba zmenit koli zmene technologie generovania mapy

**Comment by vmizenkova** [comment]
ano, pracujem na tom

**Comment by vidosuba** [comment]
treba upravit popis numpy, to com tam je, nie je uplne pravda

**Comment by vmizenkova** [comment]
dakujem, opravim to

**Comment by vmizenkova** [comment]
pandas je pouzity na vyhradenie datumov odkedy dokedy je animacia alebo odkedy dokedy su v suboroch udaje?

**Comment by vidosuba** [comment]
vybavene
