### ISSUE TITLE
Výber dňa

### ISSUE THREAD

**Issue by vidosuba** [TIS2018-FMFI/shmu#36]
Už sa môže začať kódiť výber dňa v GUI cez nejaký listView a následný callback na to v dashi

**Comment by matobernat** [comment]
Toto je teraz velmi aktualne, v subore webScripts.js je metoda changedDate(date) ktora sa zavola vzdy ked je zmeneny datum, parameter je ten aktualmny datum, tato metoda sa moze vyuzit v naslednych metodach.
