### ISSUE TITLE
Vytvorenie navrhu testovacich scenarov

### ISSUE THREAD

**Issue by pavlovator** [TIS2018-FMFI/shmu#38]
https://docs.google.com/document/d/1SMP9G0aEX2W18uT4znDye-2WEaqNJxMWPCc-z5IMoEQ/edit?usp=sharing 
Kazdy popise pridelene scenare pod svojim menom

**Comment by pavlovator** [comment]
V katalogu je napisane ze rastrova vrstva sa zobrazi az po zadani zvolenej latky, ale minule sme sa na stretnuti bavili, ze tam bude daky default... tak to teda tak aj popisem v testovacom scenari.

**Comment by matobernat** [comment]
ja som svoje testovacie scenare pridal.

**Comment by vmizenkova** [comment]
dokument zaslany cviciacemu

**Comment by pavelpetrovic** [comment]
dakujem. chapem to tak, ze toto je ta druha cast dokumentu, kde sa uz testuje cela hotova aplikacia potom, ako sa daju vsetky casti dokopy.
este by som potreboval aj tu prvu cast, kde bude napisane ako si kazdy po sebe otestuje svoju cast predtym, ako ostatnym povie, ze to ma hotovo.
a tiez by niekto iny mohol teraz skontrolovat, ci su vsetky poziadavky z katalogu poziadaviek pokryte nejakym testovacim scenarom.
inak dobra praca.

**Comment by matobernat** [comment]
kazdy by si mohol teda na zaver vytvorit maly script s testovacimi scenarmi
