### ISSUE TITLE
Implementacia - GUI (Martin)

### ISSUE THREAD

**Issue by pavlovator** [TIS2018-FMFI/shmu#39]
Tu sa pisu komentare ohladom GUI implementacie

**Comment by vidosuba** [comment]
gui sa musi prepisat z dash_html komponentov do normalneho html/css/javascript....kludne na tom mozes robit, na mapu len vyclen daky div, potom to dame dokopy....

**Comment by matobernat** [comment]
spravil som zatial zakladnu verziu GUI, budem na tom dalej pracovat

**Comment by matobernat** [comment]
david, potrebujem aby si vyskusal prepojit moj html subor s projektom aby sme vedeli ci to funguje ok, dakujem.

**Comment by vidosuba** [comment]
pozrem sa na to

**Comment by matobernat** [comment]
GUI je vytvorene
