### ISSUE TITLE
Implementacia - Generovanie mapy (David)

### ISSUE THREAD

**Issue by pavlovator** [TIS2018-FMFI/shmu#41]
Tu sa pisu komentare o generovani mapy.

**Comment by vidosuba** [comment]
generovanie- predbezna verzia: pri vybere dna sa vygeneruju tiffka pre vsetky hodiny, poslu sa...a potom sa to uz bude menit len v browseri...kym sa to nacita, tam bude nejake progress bar..alebo tociace koliesko :D

**Comment by vidosuba** [comment]
nahrana prva verzia s novym generovanim ako novy branch - verzia2

**Comment by matobernat** [comment]
myslim david ze generaciu mapy uz si celu zvladol na jednotku, toto issue mozeme zavriet
