### ISSUE TITLE
Filip, treba vygenerovat dalsi JSON o polutantoch

### ISSUE THREAD

**Issue by matobernat** [TIS2018-FMFI/shmu#65]
FIlip potrebujeme aby si spravil JSON ktory posle udaje o vsetkych pollutantoch aby som z nich mohol spravit zoznam v index.html

**Comment by pavlovator** [comment]
Nazvy pollutantov su aj v konfiguracnom subore. config.json. Vyberies vlastne vsetky kluce z "pollutents_nc".
Neriadis sa podla "pollutants_csv" lebo tie obsahuju data o nameranych hodnotach. My vykreslujeme mapu pre namodelovane hodnoty a podla nich aj bude ten zoznam.
