### ISSUE TITLE
Backend Filip, David

### ISSUE THREAD

**Issue by matobernat** [TIS2018-FMFI/shmu#67]
chalani tie komponenty su nachystane na volanie funkcii, 
potrebujem funkcie typu:
reloadTiff(date)
reloadTiff(substance)
reloadTiff(color,hour)uz som spravil.

dalej potrebujem aby sme nejako vymysleli to animovanie, to znamena ze komponent myslim ze layer(?) neviem.. by sa mohol ulozit do pola kde by boli vsetky layere s daneho dna a mohli by sme medzi nimi preskakovat.
Vobec neviem ako spravit ten cyklus tak aby bol nekonecny ale aby to aj nezablokovalo cely program..

a este by som aj potreboval matody get_min_date() get_max_date() 
neviem ci take su.

**Comment by pavlovator** [comment]
metoda get_min_date(),get_max_date() je v pollutants.py, konkretne: getCurrentMinDate() a getCurrentMaxDate(). Tie vratia minimalny datetime pre momentalne zvoleny pollutant.

**Comment by matobernat** [comment]
rozumiem dakujem.
