### ISSUE TITLE
Navrh

### ISSUE THREAD

**Issue by pavlovator** [TIS2018-FMFI/shmu#7]
Vytvorenie prvej verzie návrhu

**Comment by vidosuba** [comment]
https://docs.google.com/document/d/1HlI0xgw7FuXGlfh15JPt6lqOdpO3nwZ_7JbaEJzzeB0/edit

**Comment by vidosuba** [comment]
https://docs.google.com/document/d/1HlI0xgw7FuXGlfh15JPt6lqOdpO3nwZ_7JbaEJzzeB0/edit?usp=sharing

link na pracovnú verziu návrhu - dá sa prezerať a upravovať len s odkazom

**Comment by matobernat** [comment]
prvá verzia návrhu bola hotová, pokračujeme do finálnej verzie.
